/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/Announcement.vue')['default']
    Button: typeof import('primevue/button')['default']
    ColoredCard: typeof import('./src/components/ColoredCard.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
