# Generated by Django 5.0.4 on 2024-04-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=39, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=39, verbose_name='密码')),
                ('phone', models.CharField(max_length=39, verbose_name='电话')),
                ('email', models.EmailField(max_length=78, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('个人', '个人'), ('企业', '企业')], default='个人', max_length=39, verbose_name='身份')),
                ('avatar', models.ImageField(default='', null=True, upload_to='avatar', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=78, unique=True, verbose_name='Token')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='account.useraccount')),
            ],
        ),
    ]
