# Generated by Django 5.0.4 on 2024-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='123.jpg', null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
