# Generated by Django 5.0.4 on 2024-05-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
