# Generated by Django 5.0.4 on 2024-05-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smoke', '0002_alter_jointrecord_options_alter_smokerecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smoke.jointrecord')),
            ],
            options={
                'verbose_name_plural': '公开图片',
            },
        ),
        migrations.CreateModel(
            name='PublicSmoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smoke.smokerecord')),
            ],
            options={
                'verbose_name_plural': '公开烟雾',
            },
        ),
    ]
