# Generated by Django 5.0.4 on 2024-05-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicjoint',
            options={'verbose_name': '公开图片', 'verbose_name_plural': '公开图片'},
        ),
        migrations.AlterModelOptions(
            name='publicsmoke',
            options={'verbose_name': '公开烟雾', 'verbose_name_plural': '公开烟雾'},
        ),
    ]
