# Generated by Django 5.0.4 on 2024-05-10 09:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_useraccount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=117, verbose_name='名称')),
                ('pic_type', models.CharField(choices=[('烟雾', '烟雾'), ('图片', '图片')], default='图片', max_length=39, verbose_name='类型')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('url', models.CharField(max_length=273, verbose_name='图片地址')),
                ('visiable', models.BooleanField(default=False, verbose_name='可见性')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount', verbose_name='用户')),
            ],
            options={
                'verbose_name': '生成结果',
                'verbose_name_plural': '生成结果',
            },
        ),
    ]
