# Generated by Django 5.0.4 on 2024-05-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smoke', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jointrecord',
            options={'verbose_name_plural': '拼接结果'},
        ),
        migrations.AlterModelOptions(
            name='smokerecord',
            options={'verbose_name_plural': '烟雾生成结果'},
        ),
    ]
