# Generated by Django 5.0.4 on 2024-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='url',
            field=models.CharField(max_length=273, unique=True, verbose_name='图片地址'),
        ),
    ]
