# Generated by Django 5.0.4 on 2024-05-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smoke', '0002_alter_jointrecord_options_alter_smokerecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jointrecord',
            options={'verbose_name': '拼接结果', 'verbose_name_plural': '拼接结果'},
        ),
        migrations.AlterModelOptions(
            name='smokerecord',
            options={'verbose_name': '烟雾生成结果', 'verbose_name_plural': '烟雾生成结果'},
        ),
    ]
