# Generated by Django 5.0.4 on 2024-05-07 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=156, verbose_name='标题')),
                ('content', models.CharField(max_length=3900, verbose_name='内容')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
            ],
        ),
    ]
