# Generated by Django 5.0.4 on 2024-05-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(max_length=3900, verbose_name='内容'),
        ),
    ]
