# Generated by Django 5.0.4 on 2024-05-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.CharField(default='管理员', max_length=39, verbose_name='发布者'),
        ),
    ]
