# Generated by Django 5.0.4 on 2024-05-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_announcement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='intro',
            field=models.CharField(default='我是简介', max_length=234, verbose_name='简介'),
        ),
    ]
